### PR TITLE
overrided stubs #209

### PR DESCRIPTION
**Pull request by honarkhah**
fix

### CODE REVIEW

**Comment by joaosalless** [comment]
Check the project name and project repository in composer.json file.
It was modified in the pull request. Is correct?

Thank you!

**Comment by honarkhah** [comment]
fix and new pull request send.
thanks for review.

**Comment by Belphemur** [comment]
I'm confused. Does this PR mean @andersao gave up his package to @honarkhah  ?

@ionut-tanasa was that the wanted effect ?

**Comment by mvpasarel** [comment]
@ionut-tanasa You should merge #217 as well. It a rollback for the package name

**Pull request merged**
