### PR TITLE
add some conditions

### PR DESCRIPTION
**Pull request by nghiennet89**

### CODE REVIEW

**Comment by bsormagec** [comment]
Can you add readme examples @nghiennet89. Then we can merge it.

Thank you.

**Comment by nghiennet89** [comment]
> Can you add readme examples @nghiennet89. Then we can merge it.
> 
> Thank you.

OK I will update it

**Comment by nghiennet89** [comment]
@bsormagec : please merge it, thank you.

**Comment by bsormagec** [comment]
> @bsormagec : please merge it, thank you.

can you add some example to how to use from request's.

Thank you.

**Comment by nghiennet89** [comment]
> > @bsormagec : please merge it, thank you.
> 
> can you add some example to how to use from request's.
> 
> Thank you.

I write on current example in Readme document, which use query findWhere with more options.
As I explained, It support to query with DATE, MONTH, YEAR on date-time fields, can query with IN or NOTIN, etc ...
This way make us more flexible to get data from "where" array. I think this document is enough to understand. Could you please merge it ?

**Comment by nghiennet89** [comment]
Please merge this request, I need it for my project, thank you.

**Pull request merged**
