### PR TITLE
updateWhere method for updates using other fields than pk

### PR DESCRIPTION
**Pull request by giordanolima**
updateWhere method for updates using other fields than pk

### CODE REVIEW

**Comment by MatheusNaldi** [comment]
I need this

**Comment by kalemdzievski** [comment]
Also need this. Can't find out how to do a multiple update.

**Comment by eullercristian** [comment]
@giordanolima The method was added yesterday in the BaseRepository, check please. Thanks for PR.

**Comment by SDLyu** [comment]
I can't find any related `updateWhere` function 😕 
Can anyone help to point out what function I can use?

**Pull request closed without merging**
