### PR TITLE
Update syntax on php files and readme

### PR DESCRIPTION
**Pull request by BafS**
I updated the syntax to PSR-2. Some files had mixed styles.

### CODE REVIEW

**Comment by BafS** [comment]
Will this pull request be merged?

**Comment by BafS** [comment]
Still not any new ? We should really clean the code style and the readme.

**Comment by johannesschobel** [comment]
i think this would be good :+1:

**Comment by BafS** [comment]
Now there are some conflicts but I can fix them if a collaborator could respond.

**Comment by eullercdr** [comment]
Please @BafS , resolve conflits or send-me a new PR.

**Comment by BafS** [comment]
I fixed the conflicts.

**Comment by BafS** [comment]
@eullercdr any news ?

**Comment by BafS** [comment]
@andersao or @eullercdr ?

**Comment by BafS** [comment]
again... @andersao or @eullercdr ?

**Comment by marcus-campos** [comment]
@eullercdr este branch está pronto para ser aceito

**Comment by BafS** [comment]
Why is this PR closed ?

**Comment by bsormagec** [comment]
It has many conflicts and old refactor many thing changed after this PR

**Pull request closed without merging**
