### PR TITLE
Laravel 6.0 compatibility

### PR DESCRIPTION
**Pull request by khairilanuar**
* replace all deprecated laravel 5.x str_* to Str helper static call

### CODE REVIEW

**Comment by eullercdr** [comment]
@khairilanuar This changes is compatibility with other versions of Laravel or some 6?

**Comment by khairilanuar** [comment]
Hi @eullercdr Laravel has dropped String & Array helpers in Laravel version 6.0. you can see it here: https://laravel.com/docs/6.0/upgrade#helpers . We are urged to use `Str::` and `Arr::` directly instead.

However if you merged this fix I'm afraid it will break for Lumen users, but without this fix generator command will not work in Laravel 6.0

**Comment by lloricode** [comment]
@eullercdr yes it is deprecated, it will remove in laravel 6

https://laravel.com/docs/6.0/upgrade#helpers

**Comment by lloricode** [comment]
@khairilanuar @eullercdr , they can install this https://github.com/laravel/helpers if this will need, after merging this

**Comment by lloricode** [comment]
just to make sure we do not use deprecated functions

**Comment by lloricode** [comment]
@eullercdr can we have this? because laravel 6 alread released, this helper functions already remove also

thank you

**Comment by kuzik** [comment]
I have an issue with installing this package in the Laravel 6 project because `prettus/laravel-validation` still require `illuminate/support: ~5.4`
Are you able to install this package in your L6 project?

**Comment by lloricode** [comment]
maybe the solution is make a PR to make validation optinal in this package

**Comment by kuzik** [comment]
This can break projects which use this validation. `prettus/laravel-validation` will support Laravel6 soon maybe it can be better to wait for approve this PR  https://github.com/andersao/laravel-validator/pull/35

**Comment by Yannik-Slym** [comment]
> @khairilanuar This changes is compatibility with other versions of Laravel or some 6?
5.7 and higher version

**Comment by eullercdr** [comment]
Dears sorry for delay. I am very busy days. 
I'll have a look as soon as possible!

**Comment by khairilanuar** [comment]
Hi @kuzik , @eullercdr @Yannik-Slym I am sorry for the delay, it is a long holiday here in my country. 
I also forked prettus/laravel-validation and have it compatible with Laravel 6. I can submit pull request for prettus/laravel-validation to make it compatible with L6. 

Please have a look at my fork at https://github.com/khairilanuar/laravel-repositoryto get some idea

**Pull request merged**
