### PR TITLE
add values parameter to firstOrCreate method

### PR DESCRIPTION
**Pull request by takatost**

### CODE REVIEW

**Comment by eullercristian** [comment]
Its really necessary, because the signature of method is `Example firstOrCreate(['name' => 'Something']);`

**Comment by joaosalless** [comment]
The `$values` parameter exists only in Laravel 5.3 or higher.This PR would make the repository method firstOrCreate incompatible with the Laravel 5.2 or less firstOrCreate method.

**Comment by eullercristian** [comment]
Exactly @joaosalless , i am trying keep the package common in all versions of laravel. I will think about implementation of new features for new versions of Laravel. Maybe a new tag 3.0.0 could be create, i will plain this question.

**Comment by GertjanRoke** [comment]
@joaosalless But it will not give an error, people that are using Laravel 5.2 or less just can only use the first param.

Maybe by just adding a comment to the `@param` to inform them about the usage of it.
Because people that keep their Laravel update now need to adjust for people that stick to older versions.
Please don't get me wrong but I think that's the wrong mindset.

**Pull request closed without merging**
