### PR TITLE
Fix Problem using method deleteWhere. (fix #242)

### LINKED ISSUE #242: Problem using method deleteWhere
Dear, 

I have the code bellow

`$this->repoPagamento->deleteWhere(['recibo_id' => $recibo]);`

When i use this method deleteWhere, i have the issue

 `Argument 2 passed to PrettusRepositoryEventsRepositoryEventBase::__construct() must be an instance of IlluminateDatabaseEloquentModel, instance of IlluminateDatabaseEloquentBuilder given, called in PrettusRepositoryEloquentBaseRepository.php on line 587`

Its a issue using this method deleteWhere?

### PR DESCRIPTION
**Pull request by joaosalless**

### CODE REVIEW

**Comment by eullercristian** [comment]
Please @andersao take a look in PRs. This package is very useful. Thanks a lot.

**Comment by eullercristian** [comment]
This repository is abandoned? What´s happens with PRs? @andersao @ionut-tanasa Can we help us?

**Comment by Numline1** [comment]
Hello @ionut-tanasa - was this ever merged/added? The current version still uses $this->model

**Comment by callmez** [comment]
same problem need merge!

**Pull request merged**
