### PR TITLE
fix bug 638

### LINKED ISSUE #638: Call to undefined function Prettus\Repository\Generators\Commands\snake_case()
Error on line: 69 in file RepositoryCommand.php on run command "php artisan make:entity my_entity"

bug

A simple solution to the problem is to change the function call from line 69. I will be sending the corresponding PR to the question.

### PR DESCRIPTION
**Pull request by GCarneiroA**
Fix #638

### CODE REVIEW

**Comment by eullercdr** [comment]
@GCarneiroA this repository is using by many peoples, and projects. Can you update your code, checking the compatibility between all versions of laravel? Thanks

**Comment by trungtrandinh198** [comment]
> @GCarneiroA this repository is using by many peoples, and projects. Can you update your code, checking the compatibility between all versions of laravel? Thanks



> @GCarneiroA this repository is using by many peoples, and projects. Can you update your code, checking the compatibility between all versions of laravel? Thanks

I see this problem with laravel 6,

**Comment by mattford** [comment]
There are a lot of other references to those functions throughout the lib, it'd probably be better to cover all of them if possible, hopefully the Str::xxx version of the fn's are supported in historical versions of Laravel.

The short term workaround is to add `laravel/helpers` as a dependency to projects which are using l5-repository

**Comment by mattford** [comment]
I've created https://github.com/andersao/l5-repository/pull/663 to replace all instances of the helper fn's with Support classes

**Comment by bsormagec** [comment]
Fixed #625

**Pull request closed without merging**
