### PR TITLE
No more AppNamespaceDetectorTrait in L5.4

### PR DESCRIPTION
**Pull request by KhaledSMQ**
update for L5.4

### CODE REVIEW

**Comment by vesper8** [comment]
According to this post it's been renamed to DetectsApplicationNamespace ?

http://igniz87.hatenablog.com/entry/2017/01/25/122435

Anyway should be a quick fix.. would appreciate if you could add it soon :)

Thanks!

**Comment by eullercristian** [comment]
Plese @ionut-tanasa , @andersao , fix the problem! Its package is so useful for us! Thanks

**Comment by 42antoine** [comment]
GoGoGo! We need the laravel 5.4 update!

**Comment by gordi256** [comment]
//use Illuminate\Console\AppNamespaceDetectorTrait;
use Illuminate\Console\DetectsApplicationNamespace;


abstract class Generator
{

  //  use AppNamespaceDetectorTrait;
  use DetectsApplicationNamespace;

**Comment by branchzero** [comment]
@eullercristian Could you have a time to merge one of the Laravel 5.4 compatible PR to make it work with Laravel 5.4? Thank you.

**Comment by eullercristian** [comment]
@branchzero Yes. Its working now in Laravel 5.4 please verify! :)

**Pull request merged**
